import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        {children}

        <Toaster
            position="top-right"
            richColors
            toastOptions={{
                classNames: {
                    toast:
                        "w-[520px] max-w-[92vw] rounded-xl border border-slate-200 bg-white shadow-lg",
                    title: "text-sm font-medium text-slate-900",
                    description: "text-sm text-slate-600",
                    success:
                        "border-emerald-200 bg-emerald-50",
                    error:
                        "border-red-200 bg-red-50",
                    warning:
                        "border-amber-200 bg-amber-50",
                    info:
                        "border-blue-200 bg-blue-50",
                },
            }}
        />
        </body>
        </html>
    );
}
